<?php

    namespace App\Http\Resources\Schedule;

    use Illuminate\Http\JsonResponse;
    use Illuminate\Http\Request;
    use Illuminate\Http\Resources\Json\JsonResource;

    class ScheduleAlreadyExistsResource extends JsonResource
    {
        public function __construct()
        {

        }

        public function withResponse(Request $request, JsonResponse $response)
        {
            parent::withResponse($request, $response->setStatusCode(401)); // TODO: Change the autogenerated stub
        }

        /**
         * Transform the resource into an array.
         *
         * @param  Request  $request
         * @return array
         */
        public function toArray($request)
        {
            return [
                'message' => 'Schedule Already Exists.',

            ];
        }
    }
