<?php

    namespace App\Http\Resources\User;

    use Illuminate\Http\JsonResponse;
    use Illuminate\Http\Request;
    use Illuminate\Http\Resources\Json\JsonResource;
    use Throwable;

    class UnableToLoginUserResource extends JsonResource
    {
        protected Throwable $e;

        public function __construct(Throwable $e)
        {
            $this->e = $e;
        }

        public function withResponse(Request $request, JsonResponse $response)
        {
            parent::withResponse($request, $response->setStatusCode(403)); // TODO: Change the autogenerated stub
        }

        /**
         * Transform the resource into an array.
         *
         * @param  Request  $request
         * @return array<string, mixed>
         */
        public function toArray($request)
        {

            return [
                'message' => "Login unsuccussfully.",
            ];
        }
    }
